### ISSUE TITLE
add to installer?

### ISSUE THREAD

**Issue by nodoubtman** [jnthas/cw-cf-0x05#1]
Hi. You should add it to your installer... :)

Thanks.
Marc.

**Comment by jnthas** [comment]
I'm on it! Still implementing.. I let you know when it's available ;)

**Comment by nodoubtman** [comment]
Oh ehheh

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jnthas** [comment]
@nodoubtman first version of pacman is released!
